/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserId = IDL.Text;
export const Role = IDL.Variant({ 'Member' : IDL.Null, 'Admin' : IDL.Null });
export const ClaimId = IDL.Nat;
export const AnnouncementId = IDL.Nat;
export const ClaimStatus = IDL.Variant({
  'Approved' : IDL.Null,
  'Rejected' : IDL.Null,
  'Pending' : IDL.Null,
});
export const Timestamp = IDL.Int;
export const Claim = IDL.Record({
  'id' : ClaimId,
  'status' : ClaimStatus,
  'memberId' : UserId,
  'createdAt' : Timestamp,
  'notes' : IDL.Opt(IDL.Text),
  'amount' : IDL.Nat,
});
export const MemberStats = IDL.Record({
  'approvedCount' : IDL.Nat,
  'totalApprovedAmount' : IDL.Nat,
});
export const Announcement = IDL.Record({
  'id' : AnnouncementId,
  'title' : IDL.Text,
  'authorId' : UserId,
  'body' : IDL.Text,
  'createdAt' : Timestamp,
});
export const LoginResult = IDL.Variant({
  'Ok' : IDL.Record({
    'displayName' : IDL.Text,
    'userId' : UserId,
    'role' : Role,
  }),
  'InvalidCredentials' : IDL.Null,
});

export const idlService = IDL.Service({
  'adminRegisterUser' : IDL.Func(
      [UserId, UserId, IDL.Text, IDL.Text, Role],
      [IDL.Bool],
      [],
    ),
  'approveClaim' : IDL.Func([IDL.Text, ClaimId], [IDL.Bool], []),
  'createAnnouncement' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text],
      [AnnouncementId],
      [],
    ),
  'deleteAnnouncement' : IDL.Func([IDL.Text, AnnouncementId], [IDL.Bool], []),
  'getMyClaims' : IDL.Func([IDL.Text], [IDL.Vec(Claim)], ['query']),
  'getMyStats' : IDL.Func([IDL.Text], [MemberStats], ['query']),
  'getPendingClaims' : IDL.Func([IDL.Text], [IDL.Vec(Claim)], ['query']),
  'getRole' : IDL.Func([UserId], [IDL.Opt(Role)], ['query']),
  'listAllClaims' : IDL.Func([IDL.Text], [IDL.Vec(Claim)], ['query']),
  'listAnnouncements' : IDL.Func([], [IDL.Vec(Announcement)], ['query']),
  'login' : IDL.Func([UserId, IDL.Text], [LoginResult], []),
  'registerMember' : IDL.Func([UserId, IDL.Text, IDL.Text], [IDL.Bool], []),
  'rejectClaim' : IDL.Func([IDL.Text, ClaimId], [IDL.Bool], []),
  'submitClaim' : IDL.Func(
      [IDL.Text, IDL.Nat, IDL.Opt(IDL.Text)],
      [ClaimId],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserId = IDL.Text;
  const Role = IDL.Variant({ 'Member' : IDL.Null, 'Admin' : IDL.Null });
  const ClaimId = IDL.Nat;
  const AnnouncementId = IDL.Nat;
  const ClaimStatus = IDL.Variant({
    'Approved' : IDL.Null,
    'Rejected' : IDL.Null,
    'Pending' : IDL.Null,
  });
  const Timestamp = IDL.Int;
  const Claim = IDL.Record({
    'id' : ClaimId,
    'status' : ClaimStatus,
    'memberId' : UserId,
    'createdAt' : Timestamp,
    'notes' : IDL.Opt(IDL.Text),
    'amount' : IDL.Nat,
  });
  const MemberStats = IDL.Record({
    'approvedCount' : IDL.Nat,
    'totalApprovedAmount' : IDL.Nat,
  });
  const Announcement = IDL.Record({
    'id' : AnnouncementId,
    'title' : IDL.Text,
    'authorId' : UserId,
    'body' : IDL.Text,
    'createdAt' : Timestamp,
  });
  const LoginResult = IDL.Variant({
    'Ok' : IDL.Record({
      'displayName' : IDL.Text,
      'userId' : UserId,
      'role' : Role,
    }),
    'InvalidCredentials' : IDL.Null,
  });
  
  return IDL.Service({
    'adminRegisterUser' : IDL.Func(
        [UserId, UserId, IDL.Text, IDL.Text, Role],
        [IDL.Bool],
        [],
      ),
    'approveClaim' : IDL.Func([IDL.Text, ClaimId], [IDL.Bool], []),
    'createAnnouncement' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text],
        [AnnouncementId],
        [],
      ),
    'deleteAnnouncement' : IDL.Func([IDL.Text, AnnouncementId], [IDL.Bool], []),
    'getMyClaims' : IDL.Func([IDL.Text], [IDL.Vec(Claim)], ['query']),
    'getMyStats' : IDL.Func([IDL.Text], [MemberStats], ['query']),
    'getPendingClaims' : IDL.Func([IDL.Text], [IDL.Vec(Claim)], ['query']),
    'getRole' : IDL.Func([UserId], [IDL.Opt(Role)], ['query']),
    'listAllClaims' : IDL.Func([IDL.Text], [IDL.Vec(Claim)], ['query']),
    'listAnnouncements' : IDL.Func([], [IDL.Vec(Announcement)], ['query']),
    'login' : IDL.Func([UserId, IDL.Text], [LoginResult], []),
    'registerMember' : IDL.Func([UserId, IDL.Text, IDL.Text], [IDL.Bool], []),
    'rejectClaim' : IDL.Func([IDL.Text, ClaimId], [IDL.Bool], []),
    'submitClaim' : IDL.Func(
        [IDL.Text, IDL.Nat, IDL.Opt(IDL.Text)],
        [ClaimId],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };