/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Announcement {
  'id' : AnnouncementId,
  'title' : string,
  'authorId' : UserId,
  'body' : string,
  'createdAt' : Timestamp,
}
export type AnnouncementId = bigint;
export interface Claim {
  'id' : ClaimId,
  'status' : ClaimStatus,
  'memberId' : UserId,
  'createdAt' : Timestamp,
  'notes' : [] | [string],
  'amount' : bigint,
}
export type ClaimId = bigint;
export type ClaimStatus = { 'Approved' : null } |
  { 'Rejected' : null } |
  { 'Pending' : null };
export type LoginResult = {
    'Ok' : { 'displayName' : string, 'userId' : UserId, 'role' : Role }
  } |
  { 'InvalidCredentials' : null };
export interface MemberStats {
  'approvedCount' : bigint,
  'totalApprovedAmount' : bigint,
}
export type Role = { 'Member' : null } |
  { 'Admin' : null };
export type Timestamp = bigint;
export type UserId = string;
export interface _SERVICE {
  'adminRegisterUser' : ActorMethod<
    [UserId, UserId, string, string, Role],
    boolean
  >,
  'approveClaim' : ActorMethod<[string, ClaimId], boolean>,
  'createAnnouncement' : ActorMethod<[string, string, string], AnnouncementId>,
  'deleteAnnouncement' : ActorMethod<[string, AnnouncementId], boolean>,
  'getMyClaims' : ActorMethod<[string], Array<Claim>>,
  'getMyStats' : ActorMethod<[string], MemberStats>,
  'getPendingClaims' : ActorMethod<[string], Array<Claim>>,
  'getRole' : ActorMethod<[UserId], [] | [Role]>,
  'listAllClaims' : ActorMethod<[string], Array<Claim>>,
  'listAnnouncements' : ActorMethod<[], Array<Announcement>>,
  'login' : ActorMethod<[UserId, string], LoginResult>,
  'registerMember' : ActorMethod<[UserId, string, string], boolean>,
  'rejectClaim' : ActorMethod<[string, ClaimId], boolean>,
  'submitClaim' : ActorMethod<[string, bigint, [] | [string]], ClaimId>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];