/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface Claim {
    id: ClaimId;
    status: ClaimStatus;
    memberId: UserId;
    createdAt: Timestamp;
    notes?: string;
    amount: bigint;
}
export type UserId = string;
export type Timestamp = bigint;
export interface Announcement {
    id: AnnouncementId;
    title: string;
    authorId: UserId;
    body: string;
    createdAt: Timestamp;
}
export interface MemberStats {
    approvedCount: bigint;
    totalApprovedAmount: bigint;
}
export type LoginResult = {
    __kind__: "Ok";
    Ok: {
        displayName: string;
        userId: UserId;
        role: Role;
    };
} | {
    __kind__: "InvalidCredentials";
    InvalidCredentials: null;
};
export type AnnouncementId = bigint;
export type ClaimId = bigint;
export enum ClaimStatus {
    Approved = "Approved",
    Rejected = "Rejected",
    Pending = "Pending"
}
export enum Role {
    Member = "Member",
    Admin = "Admin"
}
export interface backendInterface {
    adminRegisterUser(callerId: UserId, newUserId: UserId, password: string, displayName: string, role: Role): Promise<boolean>;
    approveClaim(callerId: string, id: ClaimId): Promise<boolean>;
    createAnnouncement(callerId: string, title: string, body: string): Promise<AnnouncementId>;
    deleteAnnouncement(callerId: string, id: AnnouncementId): Promise<boolean>;
    getMyClaims(callerId: string): Promise<Array<Claim>>;
    getMyStats(callerId: string): Promise<MemberStats>;
    getPendingClaims(callerId: string): Promise<Array<Claim>>;
    getRole(userId: UserId): Promise<Role | null>;
    listAllClaims(callerId: string): Promise<Array<Claim>>;
    listAnnouncements(): Promise<Array<Announcement>>;
    login(userId: UserId, password: string): Promise<LoginResult>;
    registerMember(userId: UserId, password: string, displayName: string): Promise<boolean>;
    rejectClaim(callerId: string, id: ClaimId): Promise<boolean>;
    submitClaim(callerId: string, amount: bigint, notes: string | null): Promise<ClaimId>;
}
import type { Claim as _Claim, ClaimId as _ClaimId, ClaimStatus as _ClaimStatus, LoginResult as _LoginResult, Role as _Role, Timestamp as _Timestamp, UserId as _UserId } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async adminRegisterUser(arg0: UserId, arg1: UserId, arg2: string, arg3: string, arg4: Role): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.adminRegisterUser(arg0, arg1, arg2, arg3, to_candid_Role_n1(this._uploadFile, this._downloadFile, arg4));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminRegisterUser(arg0, arg1, arg2, arg3, to_candid_Role_n1(this._uploadFile, this._downloadFile, arg4));
            return result;
        }
    }
    async approveClaim(arg0: string, arg1: ClaimId): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.approveClaim(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.approveClaim(arg0, arg1);
            return result;
        }
    }
    async createAnnouncement(arg0: string, arg1: string, arg2: string): Promise<AnnouncementId> {
        if (this.processError) {
            try {
                const result = await this.actor.createAnnouncement(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createAnnouncement(arg0, arg1, arg2);
            return result;
        }
    }
    async deleteAnnouncement(arg0: string, arg1: AnnouncementId): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteAnnouncement(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteAnnouncement(arg0, arg1);
            return result;
        }
    }
    async getMyClaims(arg0: string): Promise<Array<Claim>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyClaims(arg0);
                return from_candid_vec_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyClaims(arg0);
            return from_candid_vec_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMyStats(arg0: string): Promise<MemberStats> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyStats(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyStats(arg0);
            return result;
        }
    }
    async getPendingClaims(arg0: string): Promise<Array<Claim>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPendingClaims(arg0);
                return from_candid_vec_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPendingClaims(arg0);
            return from_candid_vec_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async getRole(arg0: UserId): Promise<Role | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getRole(arg0);
                return from_candid_opt_n9(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getRole(arg0);
            return from_candid_opt_n9(this._uploadFile, this._downloadFile, result);
        }
    }
    async listAllClaims(arg0: string): Promise<Array<Claim>> {
        if (this.processError) {
            try {
                const result = await this.actor.listAllClaims(arg0);
                return from_candid_vec_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listAllClaims(arg0);
            return from_candid_vec_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async listAnnouncements(): Promise<Array<Announcement>> {
        if (this.processError) {
            try {
                const result = await this.actor.listAnnouncements();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listAnnouncements();
            return result;
        }
    }
    async login(arg0: UserId, arg1: string): Promise<LoginResult> {
        if (this.processError) {
            try {
                const result = await this.actor.login(arg0, arg1);
                return from_candid_LoginResult_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.login(arg0, arg1);
            return from_candid_LoginResult_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async registerMember(arg0: UserId, arg1: string, arg2: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.registerMember(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.registerMember(arg0, arg1, arg2);
            return result;
        }
    }
    async rejectClaim(arg0: string, arg1: ClaimId): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.rejectClaim(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.rejectClaim(arg0, arg1);
            return result;
        }
    }
    async submitClaim(arg0: string, arg1: bigint, arg2: string | null): Promise<ClaimId> {
        if (this.processError) {
            try {
                const result = await this.actor.submitClaim(arg0, arg1, to_candid_opt_n15(this._uploadFile, this._downloadFile, arg2));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitClaim(arg0, arg1, to_candid_opt_n15(this._uploadFile, this._downloadFile, arg2));
            return result;
        }
    }
}
function from_candid_ClaimStatus_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ClaimStatus): ClaimStatus {
    return from_candid_variant_n7(_uploadFile, _downloadFile, value);
}
function from_candid_Claim_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Claim): Claim {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_LoginResult_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _LoginResult): LoginResult {
    return from_candid_variant_n13(_uploadFile, _downloadFile, value);
}
function from_candid_Role_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Role): Role {
    return from_candid_variant_n11(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Role]): Role | null {
    return value.length === 0 ? null : from_candid_Role_n10(_uploadFile, _downloadFile, value[0]);
}
function from_candid_record_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    displayName: string;
    userId: _UserId;
    role: _Role;
}): {
    displayName: string;
    userId: UserId;
    role: Role;
} {
    return {
        displayName: value.displayName,
        userId: value.userId,
        role: from_candid_Role_n10(_uploadFile, _downloadFile, value.role)
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _ClaimId;
    status: _ClaimStatus;
    memberId: _UserId;
    createdAt: _Timestamp;
    notes: [] | [string];
    amount: bigint;
}): {
    id: ClaimId;
    status: ClaimStatus;
    memberId: UserId;
    createdAt: Timestamp;
    notes?: string;
    amount: bigint;
} {
    return {
        id: value.id,
        status: from_candid_ClaimStatus_n6(_uploadFile, _downloadFile, value.status),
        memberId: value.memberId,
        createdAt: value.createdAt,
        notes: record_opt_to_undefined(from_candid_opt_n8(_uploadFile, _downloadFile, value.notes)),
        amount: value.amount
    };
}
function from_candid_variant_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    Member: null;
} | {
    Admin: null;
}): Role {
    return "Member" in value ? Role.Member : "Admin" in value ? Role.Admin : value;
}
function from_candid_variant_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    Ok: {
        displayName: string;
        userId: _UserId;
        role: _Role;
    };
} | {
    InvalidCredentials: null;
}): {
    __kind__: "Ok";
    Ok: {
        displayName: string;
        userId: UserId;
        role: Role;
    };
} | {
    __kind__: "InvalidCredentials";
    InvalidCredentials: null;
} {
    return "Ok" in value ? {
        __kind__: "Ok",
        Ok: from_candid_record_n14(_uploadFile, _downloadFile, value.Ok)
    } : "InvalidCredentials" in value ? {
        __kind__: "InvalidCredentials",
        InvalidCredentials: value.InvalidCredentials
    } : value;
}
function from_candid_variant_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    Approved: null;
} | {
    Rejected: null;
} | {
    Pending: null;
}): ClaimStatus {
    return "Approved" in value ? ClaimStatus.Approved : "Rejected" in value ? ClaimStatus.Rejected : "Pending" in value ? ClaimStatus.Pending : value;
}
function from_candid_vec_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Claim>): Array<Claim> {
    return value.map((x)=>from_candid_Claim_n4(_uploadFile, _downloadFile, x));
}
function to_candid_Role_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Role): _Role {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: string | null): [] | [string] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Role): {
    Member: null;
} | {
    Admin: null;
} {
    return value == Role.Member ? {
        Member: null
    } : value == Role.Admin ? {
        Admin: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
